---
# configure services

- name: define a service to run production site
  become: yes
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service

- name: enable system service
  systemd:
    name: app
    enabled: true
    state: restarted
