- name: remove temporary build
  command: rm -rf {{base_path}}.tmp

- name: temp build directory exists
  file: path={{base_path}}.tmp state=directory

- name: code is synchronized via git to temp directory
  git: dest={{base_path}}.tmp repo={{git_repo}} version={{commit}}
  when: env != 'development'

# The `npm` Ansible module cannot be used on this system because it is
# incompatible with the version of the npm CLI which is available on the
# machine.
- name: Install Node.js dependencies
  command: npm install
  args:
    chdir: "{{base_path}}.tmp"

- name: production version of the application has been built
  command: npm run build
  args:
    chdir: "{{base_path}}.tmp"

- name: current production build is removed
  command: rm -rf {{base_path}}

- name: new production build is in place
  command: mv {{base_path}}.tmp {{base_path}}
